### ISSUE TITLE
Chrome and Chromium backups are entire folder of extension settings

### ISSUE THREAD

**Issue by walshie4** [walshie4/backup-RES-Settings#2]
Until I can look further into how Chrome and Chromium choose where to put individual extension settings files the Chrome and Chromium will be detected if the extensions settings folder for all Chrome and/or Chromium extensions is detected.

**Comment by jewel-andraia** [comment]
FYI,  Chrome creates separate folders for extension data if you set up multiple profiles on your browser.  (I have heard this but not personally verified.)

**Comment by jewel-andraia** [comment]
@gavin19 reported "Doesn't work for me in Win 8.1. It detects Windows but not the install."

**Comment by gavin19** [comment]
It doesn't find the Chromium or Chrome installs. 'Detect OS' works fine.

**Comment by walshie4** [comment]
What OS is reported when 'Detect OS' is run?

**Comment by gavin19** [comment]
Literally 'windows 8'.

**Comment by walshie4** [comment]
Try the new release, should hopefully fix the problem.

**Comment by gavin19** [comment]
Still doesn't work. Appears to be an issue with the paths. The check is made for APPDATA, ie C:\Users\User\AppData\Roaming (which always exists AFAIK), but the vast majority of Chrome/ium installs will be to LOCALAPPDATA, C:\Users\User\AppData\Local. `chrome78` ends up being
C:\Users\User\AppData\Roaming\Local... which doesn't exist.

**Comment by walshie4** [comment]
Where does the Roaming come from?

**Comment by gavin19** [comment]
The %APPDATA% variable points to AppData\Roaming (as does `user.home` for me on a standalone PC). There is a check if that exists, which it does, then the CHROME_PATH_WIN78 string is appended. It has 'Local' at the beginning, so it points to a non-existent location.

Firefox stores its profiles in AppData\Roaming\Firefox.. but Chrome uses AppData\Local\Google\Chrome.. by default. It's only ever in Roaming for those people that specifically install it there, on a domain/network. It seems to me that you'd need to check if AppData\Local\Google\Chrome exists, failing that, that AppData\Roaming\Google\Chrome exists.

**Comment by walshie4** [comment]
Sorry for the super long delay, been busy and this project just kinda fell off my plate. However I believe the issue should be fixed in the most recent release. Please let me know otherwise and I'll investigate further. https://github.com/walshie4/backup-RES-Settings/releases/tag/V0.1.2

**Comment by walshie4** [comment]
After looking into this further the issue still seems to be present, however should be fixed soon.

**Comment by walshie4** [comment]
Latest commit (f7c8242dace99437912800d1fcca15d27e2eae08) should fix the issue @gavin19 was having, although this issue needs to stay open until I can address the original issue. Also I can't test this until I have access to a Windows machine.

**Comment by walshie4** [comment]
Latest commit and release V0.2.0 should fix this issue.
