### ISSUE TITLE
No information on how to restore or convert

### ISSUE THREAD

**Issue by signe** [walshie4/backup-RES-Settings#6]
There is no information either in the app itself, or in the README regarding how to restore data, or how to convert data to another browser format.

Backups without the capability to restore is useless to a user.

**Comment by walshie4** [comment]
To restore simply move the backup to where the settings file was located. All locations can be found on the RES wiki. As for converting, as of right now this application does not have that capability.

This will eventually be automated once I have more time to work on it.

**Comment by jewel-andraia** [comment]
oh, sorry, I might mistakenly have touted your app as being able to migrate between apps.

**Comment by signe** [comment]
It's actually listed in the project description, as well...

![screenshot 2014-10-17 17 02 08](https://cloud.githubusercontent.com/assets/249456/4687667/0da2c224-565a-11e4-8ce7-92f206f8fe03.png)

**Comment by walshie4** [comment]
Yeah I should change that. I had hoped to include that and probably will eventually however there is no way I'll have the time in the near future. My bad.
